/**
 * Morgan HTTP Request Logger Middleware.
 * This module integrates the Morgan middleware with our custom Winston logger
 * to ensure that all incoming HTTP requests are logged consistently across the application.
 */

import morgan, { type StreamOptions } from "morgan";
import logger from "./winston.logger";
import { NODE_ENV } from "../envs";

/**
 * Winston-compatible stream for Morgan.
 * This object defines a 'write' method that Morgan calls for every request log.
 * We redirect this output to Winston's .http() severity level for centralized storage and formatting.
 */
const stream: StreamOptions = {
  // Catch the raw log message generated by Morgan.
  write: (message: string): void => {
    // Morgan appends a trailing newline (\n) by default; we trim it for clean Winston output.
    logger.http(message.trim());
  },
};

/**
 * Logic to conditionally skip logging for specific requests.
 * In this implementation, we only skip logs if we are NOT in the development environment.
 * This prevents production logs from being overwhelmed by standard HTTP telemetry.
 */
const skip = (): boolean => {
  const env = NODE_ENV;
  // returns true if we want to SILENCE the logs for the current request.
  return env !== "development";
};

/**
 * Morgan Middleware Initialization.
 * Format String: ':remote-addr :method :url :status - :response-time ms'
 * - :remote-addr: The IP address of the client (or proxy).
 * - :method: The HTTP method (GET, POST, etc.).
 * - :url: The requested path.
 * - :status: The HTTP response code.
 * - :response-time: The duration taken to process the request.
 */
const morganMiddleware = morgan(
  ":remote-addr :method :url :status - :response-time ms",
  {
    // Inject our custom Winston stream.
    stream,
    // Inject our skip logic.
    skip,
  }
);

// Export the configured middleware for registration in index.ts.
export default morganMiddleware;
