/**
 * PostgreSQL Database Table Setup Script.
 * This administrator utility automates the creation of the relational database 
 * schema required for the video transcoding application. It ensures that the 
 * 'videos' table is properly provisioned with the correct data types and constraints.
 * 
 * Logic Flow:
 * 1. Initialize a single client connection using the Neon/Postgres URI.
 * 2. Define the 'videos' schema including HLS status tracking and cloud task ARNs.
 * 3. Execute 'CREATE TABLE IF NOT EXISTS' to ensure idempotency.
 */

import pg from "pg";
import { DATABASE_URL } from "../envs";
import logger from "../logger/winston.logger";

/**
 * Main Database Orchestration Function for Postgres Setup.
 */
async function setupPostgres() {
  const connectionString = DATABASE_URL;

  // Validation: The script cannot interact with Postgres without the raw connection string.
  if (!connectionString) {
    logger.error("❌ Missing DATABASE_URL credentials. Cannot proceed with schema creation.");
    process.exit(1);
  }

  // Create and initialize the PG client using the connection string.
  const client = new pg.Client({ connectionString });
  
  // Establish the network handshake with the database.
  await client.connect();

  logger.info("🚀 Starting PostgreSQL schema synchronization...");

  /**
   * Schema Definition for 'videos' table:
   * - id: Unique UUID primary key generated by the database.
   * - title: Human-readable video name.
   * - url: The original source path in AWS S3.
   * - status: Current pipeline state (UPLOADING, QUEUED, PROCESSING, COMPLETED, FAILED).
   * - external_id: The identifier for the compute task (Docker container name or ECS Task ARN).
   * - created_at: Timestamp tracking when the entry was first added.
   */
  const createVideosTable = `
    CREATE TABLE IF NOT EXISTS videos (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      title TEXT NOT NULL,
      url TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'UPLOADING',
      external_id TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `;

  try {
    // Stage 1: Table Creation.
    // We execute the query to ensure the essential table Registry is ready for operation.
    await client.query(createVideosTable);
    logger.info("✅ Videos table Registry is ready.");
  } catch (error) {
    // Catch and log SQL-level constraint or connection failures.
    logger.error("❌ PostgreSQL schema sync failed:", error);
    process.exit(1);
  } finally {
    // Stage 2: Cleanup.
    // Explicitly end the client session to free up Neon connection slots.
    await client.end();
    logger.info("👋 Database session terminated.");
  }
}

// Execute the setup and handle the process lifecycle.
setupPostgres().then(() => {
  process.exit(0);
});
